const html = `
<p><strong>Consentimiento informado para servicios de telesalud de Foodsmart Nutrition Network</strong></p>
<p>&nbsp;</p>
<p><span style="font-weight: 400;">La telesalud usa las comunicaciones electr&oacute;nicas para que los proveedores de atenci&oacute;n de la salud ubicados en diferentes lugares puedan compartir informaci&oacute;n m&eacute;dica individual de los pacientes con el objetivo de mejorar la atenci&oacute;n que estos reciben. Los servicios de telesalud que ofrece Foodsmart Nutrition Network ("FNN", que lleva adelante sus actividades comerciales mediante los grupos de proveedores legales de Zipongo Health Provider Group, P.A., una entidad que opera con los nombres comerciales de Foodsmart Nutrition Network; Foodsmart Nutrition Network of New Jersey, P.C.; Foodsmart Nutrition Network of Kansas, P.A.; y David Ashley, MD, P.C., en conjunto, Foodsmart Nutrition Network) tambi&eacute;n pueden incluir lo siguiente: revisi&oacute;n de historias m&eacute;dicas, administraci&oacute;n remota de recetas, programaci&oacute;n de citas, intercambio de informaci&oacute;n sobre salud y servicios que no son cl&iacute;nicos, como la educaci&oacute;n de los pacientes. La informaci&oacute;n que usted brinda puede usarse para el diagn&oacute;stico, el tratamiento, el seguimiento y/o la educaci&oacute;n de los pacientes, y puede incluir cualquier combinaci&oacute;n de lo siguiente: (1) registros m&eacute;dicos y resultados de pruebas; (2) im&aacute;genes y comunicaciones asincr&oacute;nicas; (3) transmisiones en vivo de audio y video bidireccionales; (4) audio interactivo con almacenamiento y retransmisi&oacute;n; y (5) datos de salida de dispositivos m&eacute;dicos, y archivos de audio y video.</span></p>
<p>&nbsp;</p>
<p><span style="font-weight: 400;">Los sistemas de comunicaci&oacute;n electr&oacute;nica que usamos incorporan protocolos de seguridad de red y de software para proteger la confidencialidad de los datos del paciente relacionados con su identificaci&oacute;n y sus im&aacute;genes, e incluyen medidas para proteger los datos y garantizar su integridad frente a la corrupci&oacute;n intencional o involuntaria.</span></p>
<p>&nbsp;</p>
<p><span style="font-weight: 400;">Los proveedores de FNN (nuestros &ldquo;proveedores&rdquo;) son un complemento de su m&eacute;dico de atenci&oacute;n primaria y no tienen la finalidad de reemplazarlo. Su m&eacute;dico de atenci&oacute;n primaria local, si tiene uno, debe seguir siendo responsable de su atenci&oacute;n m&eacute;dica integral. Si no lo tiene, le recomendamos seriamente que busque uno.</span></p>
<p>&nbsp;</p>
<p><strong>Beneficios esperados:</strong></p>
<ul>
<li style="font-weight: 400;"><span style="font-weight: 400;">Mejor acceso a la atenci&oacute;n, ya que puede quedarse en su hogar mientras el proveedor de FNN consulta y obtiene los resultados de las pruebas en centros distantes u otros centros.</span></li>
<li style="font-weight: 400;"><span style="font-weight: 400;">Mayor eficacia en la evaluaci&oacute;n y la gesti&oacute;n de la atenci&oacute;n.</span></li>
<li style="font-weight: 400;"><span style="font-weight: 400;">Consulta con un especialista seg&uacute;n sea necesario.</span></li>
</ul>
<p>&nbsp;</p>
<p><strong>Posibles riesgos:</strong></p>
<ul>
<li style="font-weight: 400;"><span style="font-weight: 400;">Podr&iacute;a haber demoras en la evaluaci&oacute;n y el tratamiento debido a deficiencias o fallas en los equipos y las tecnolog&iacute;as.</span></li>
<li style="font-weight: 400;"><span style="font-weight: 400;">En situaciones poco frecuentes, nuestro proveedor podr&iacute;a determinar que la calidad de la informaci&oacute;n transmitida es inadecuada; en este caso, se deber&aacute; volver a programar una consulta de telesalud o una reuni&oacute;n con su m&eacute;dico de atenci&oacute;n primaria local.</span></li>
<li style="font-weight: 400;"><span style="font-weight: 400;">En situaciones muy poco frecuentes, los protocolos de seguridad podr&iacute;an fallar, por lo que la privacidad de la informaci&oacute;n m&eacute;dica personal podr&iacute;a verse afectada.</span></li>
<li style="font-weight: 400;"><span style="font-weight: 400;">En situaciones poco frecuentes, la falta de acceso a los registros m&eacute;dicos completos podr&iacute;a dar como resultado interacciones farmacol&oacute;gicas adversas, reacciones al&eacute;rgicas u otros errores en el diagn&oacute;stico.</span></li>
</ul>
<p>&nbsp;</p>
<ul>
<li style="font-weight: 400;"><span style="font-weight: 400;">Si necesita atenci&oacute;n de seguimiento o ayuda ante una reacci&oacute;n adversa al tratamiento, o si no puede comunicarse debido a una falla en los equipos o en las tecnolog&iacute;as, comun&iacute;quese con FNN llamando al 888-837-5325 o enviando un correo electr&oacute;nico a: telenutrition@foodsmart.com.</span></li>
</ul>
<p><span style="font-weight: 400;">Usted afirma que entiende y est&aacute; de acuerdo con lo siguiente:</span></p>
<p>&nbsp;</p>
<ol>
<li style="font-weight: 400;"><span style="font-weight: 400;">Mediante este documento, acepto recibir los servicios de FNN a trav&eacute;s de tecnolog&iacute;as de telesalud. Entiendo que FNN y sus proveedores ofrecen servicios m&eacute;dicos basados en la telesalud, pero que estos servicios no reemplazan la relaci&oacute;n que tengo con mi m&eacute;dico de atenci&oacute;n primaria. Entiendo tambi&eacute;n que es el proveedor de FNN el que debe determinar si mis necesidades cl&iacute;nicas espec&iacute;ficas son apropiadas para un encuentro de telesalud.</span></li>
<li style="font-weight: 400;"><span style="font-weight: 400;">Tengo derecho a comunicarme con FNN antes de mi consulta programada para elegir un proveedor alternativo o para revisar las credenciales de mi proveedor.</span></li>
<li style="font-weight: 400;"><span style="font-weight: 400;">Autorizo al consultorio de mi proveedor a comunicarse conmigo por tel&eacute;fono celular.</span></li>
<li style="font-weight: 400;"><span style="font-weight: 400;">Entiendo que las leyes federales y estatales requieren que los proveedores de atenci&oacute;n de la salud protejan la privacidad y la seguridad de la informaci&oacute;n m&eacute;dica. Entiendo que FNN tomar&aacute; medidas para asegurarse de que las personas que no est&eacute;n autorizadas no puedan obtener acceso a mi informaci&oacute;n m&eacute;dica. Entiendo que la telesalud puede incluir la comunicaci&oacute;n electr&oacute;nica de mi informaci&oacute;n m&eacute;dica personal con otros profesionales de la salud que podr&iacute;an estar ubicados en otras &aacute;reas, incluso fuera del estado.</span></li>
<li style="font-weight: 400;"><span style="font-weight: 400;">Entiendo que existe el riesgo de que haya fallas t&eacute;cnicas durante el encuentro de telesalud que escapan al control de FNN. Acepto liberar de responsabilidad a FNN por las demoras en la evaluaci&oacute;n o por la informaci&oacute;n que se pierda debido a las fallas t&eacute;cnicas mencionadas.</span></li>
<li style="font-weight: 400;"><span style="font-weight: 400;">Entiendo que tengo derecho a retener o retirar mi consentimiento para el uso de los servicios de telesalud en cualquier momento mientras dure mi atenci&oacute;n, sin que esto afecte mi derecho a recibir atenci&oacute;n o tratamiento en el futuro. Entiendo que puedo suspender o poner fin al uso de los servicios de telesalud en cualquier momento por cualquier motivo o sin tener motivo alguno. Entiendo que si tengo una emergencia m&eacute;dica, se me pedir&aacute; que llame al 9-1-1 de inmediato y que los proveedores de FNN no pueden conectarme directamente con ning&uacute;n servicio de emergencia local.</span></li>
<li style="font-weight: 400;"><span style="font-weight: 400;">Entiendo que tengo alternativas a la consulta de telesalud, como los servicios en persona, y, si decido participar en una consulta de telesalud, entiendo que algunos aspectos de los servicios que incluyen pruebas podr&iacute;an estar a cargo de personas en mi ubicaci&oacute;n, o bien llevarse a cabo en un centro de pruebas, seg&uacute;n lo indique el proveedor de FNN (por ejemplo, an&aacute;lisis de laboratorio o de sangre).</span></li>
<li style="font-weight: 400;"><span style="font-weight: 400;">Entiendo que puedo esperar obtener los beneficios previstos del uso de la telesalud en mi atenci&oacute;n, pero que no se puede asegurar ni garantizar ning&uacute;n resultado.</span></li>
<li style="font-weight: 400;"><span style="font-weight: 400;">Entiendo que mi informaci&oacute;n sobre la atenci&oacute;n de la salud puede compartirse con otras personas con fines de programaci&oacute;n y facturaci&oacute;n. Es posible que, adem&aacute;s del proveedor de FNN, haya otras personas presentes durante la consulta para operar las tecnolog&iacute;as relacionadas con la telesalud. Entiendo tambi&eacute;n que me informar&aacute;n sobre su presencia durante la consulta, por lo que tendr&eacute; el derecho a pedir lo siguiente: (1) que se omitan detalles espec&iacute;ficos de mi historial/examen m&eacute;dico que considere personalmente confidenciales; (2) que el personal no m&eacute;dico se retire del examen de telesalud; y/o (3) que se termine la consulta en cualquier momento.</span></li>
<li style="font-weight: 400;"><span style="font-weight: 400;">Entiendo que no me recetar&aacute;n ning&uacute;n medicamento para aliviar el dolor, y que no hay absolutamente ninguna garant&iacute;a de que me hagan una receta.</span></li>
<li style="font-weight: 400;"><span style="font-weight: 400;">Entiendo que, si participio en una consulta, tengo derecho a pedir una copia de mis registros m&eacute;dicos, y que tendr&eacute; que pagar un costo razonable por su preparaci&oacute;n, env&iacute;o y entrega.</span></li>
</ol>
<p>&nbsp;</p>
<p><strong>Consentimiento del paciente</strong></p>
<p><span style="font-weight: 400;">He le&iacute;do este documento detenidamente, y entiendo los riesgos y los beneficios relacionados con la consulta de telesalud. Adem&aacute;s, obtuve respuestas a las preguntas que hice sobre el procedimiento. Doy mi consentimiento informado para participar en una consulta de telesalud seg&uacute;n los t&eacute;rminos que se describen en este formulario.</span></p>
<p>&nbsp;</p>
<p><strong>Autorizaci&oacute;n para el Acceso a la Informaci&oacute;n sobre los Beneficios de Formulario</strong></p>
<p><span style="font-weight: 400;">Los Administradores de Beneficios de Farmacia (PBM, por sus siglas en ingl&eacute;s) son organizaciones que gestionan la informaci&oacute;n de los beneficios de formulario para los proveedores de seguros de salud. Los PBM son administradores independientes de programas de medicamentos recetados, que se encargan especialmente de procesar y pagar las reclamaciones sobre medicamentos recetados. Tambi&eacute;n crean y administran los formularios, que son listas de medicamentos disponibles, cubiertos por un plan de beneficios de medicamentos espec&iacute;fico.</span><span style="font-weight: 400;">&nbsp;</span></p>
<p>&nbsp;</p>
<p><span style="font-weight: 400;">Autorizo a Foodsmart Nutrition Network ("FNN", que lleva adelante sus actividades comerciales mediante los grupos de proveedores legales de Zipongo Health Provider Group, P.A., una entidad que opera con los nombres comerciales de Foodsmart Nutrition Network; Foodsmart Nutrition Network of New Jersey, P.C.; Foodsmart Nutrition Network of Kansas, P.A.; y David Ashley, MD, P.C., en conjunto, Foodsmart Nutrition Network) a obtener acceso a la informaci&oacute;n sobre mis beneficios de farmacia de forma electr&oacute;nica mediante RxHub. Con esta autorizaci&oacute;n, FNN podr&aacute; hacer lo siguiente:</span><span style="font-weight: 400;">&nbsp;</span></p>
<ul>
<li style="font-weight: 400;"><span style="font-weight: 400;">Determinar los copagos de los beneficios de farmacia y de los medicamentos de mi plan de salud.</span><span style="font-weight: 400;">&nbsp;</span></li>
<li style="font-weight: 400;"><span style="font-weight: 400;">Comprobar si mi plan cubre un medicamento recetado espec&iacute;fico (en el formulario).</span><span style="font-weight: 400;">&nbsp;</span></li>
<li style="font-weight: 400;"><span style="font-weight: 400;">Para los medicamentos que no son del formulario, mostrar alternativas de tratamiento ordenadas seg&uacute;n el nivel de preferencia (si est&aacute; disponible) por tipo de medicamento.</span></li>
<li style="font-weight: 400;"><span style="font-weight: 400;">Decidir si mi plan permite que se hagan recetas electr&oacute;nicas para las farmacias de venta por correo y, si es as&iacute;, hacer recetas electr&oacute;nicas para estas farmacias.</span></li>
<li style="font-weight: 400;"><span style="font-weight: 400;">Bajar un listado completo de todos los medicamentos que me recet&oacute; cualquiera de mis proveedores.</span></li>
</ul>
<p>&nbsp;</p>
<p><strong>Formulario de cesi&oacute;n de beneficios</strong></p>
<p>&nbsp;</p>
<p><span style="font-weight: 400;">Mediante este documento, le cedo a Foodsmart Nutrition Network ("FNN", que lleva adelante sus actividades comerciales mediante los grupos de proveedores legales de Zipongo Health Provider Group, P.A., una entidad que opera con los nombres comerciales de Foodsmart Nutrition Network; Foodsmart Nutrition Network of New Jersey, P.C.; Foodsmart Nutrition Network of Kansas, P.A.; y David Ashley, MD, P.C., en conjunto, Foodsmart Nutrition Network) todos mis derechos, t&iacute;tulos e intereses sobre cualquier tipo de seguro de salud u otros beneficios de atenci&oacute;n m&eacute;dica que un seguro pagador (incluidos Medicare, seguros privados y cualquier otro plan de salud) deba pagarme o pagar en mi nombre por el tratamiento m&eacute;dico brindado por FNN. La cesi&oacute;n tendr&aacute; validez hasta que la cancele por escrito. Autorizo a que se brinde la informaci&oacute;n apropiada que sea necesaria para procesar mi reclamaci&oacute;n m&eacute;dica. Autorizo tambi&eacute;n a que se le paguen directamente a FNN todos los beneficios del seguro que me correspondan por el tratamiento m&eacute;dico mencionado. Si un seguro pagador me paga a m&iacute; directamente, acepto pagarle de inmediato a FNN la cantidad recibida.</span></p>
<p>&nbsp;</p>
<p><span style="font-weight: 400;">Entiendo que es posible que mi seguro pagador pague una cantidad menor que la que realmente aparece en la factura de los servicios. Reconozco que sigo siendo responsable de pagarle a FNN cualquier cantidad que mi seguro pagador no pague, incluidos los cargos no cubiertos y todos los copagos y deducibles. Entiendo que, si mi seguro pide una referencia, es mi responsabilidad obtenerla antes de la cita. Si es necesario iniciar una demanda para que FNN reciba las cantidades que le debo, acepto pagar todos los gastos relacionados con la demanda, incluidos, entre otros, los honorarios de la agencia de cobros y de los abogados.</span></p>
<p>&nbsp;</p>
<p><span style="font-weight: 400;">Certifico que le&iacute; y que entiendo la informaci&oacute;n anterior, y que recib&iacute; una copia de esta. Soy el paciente, el representante legal del paciente, o bien estoy debidamente autorizado por el paciente para aceptar sus t&eacute;rminos en su nombre.</span></p>
<p><br /><br /></p>
<p><strong>Aceptaci&oacute;n del intercambio de informaci&oacute;n m&eacute;dica</strong></p>
<p>&nbsp;</p>
<p><span style="font-weight: 400;">Foodsmart Nutrition Network ("FNN", que lleva adelante sus actividades comerciales mediante los grupos de proveedores legales de Zipongo Health Provider Group, P.A., una entidad que opera con los nombres comerciales de Foodsmart Nutrition Network; Foodsmart Nutrition Network of New Jersey, P.C.; Foodsmart Nutrition Network of Kansas, P.A.; y David Ashley, MD, P.C., en conjunto, Foodsmart Nutrition Network) participa en Intercambios de Informaci&oacute;n M&eacute;dica (HIE, por sus siglas en ingl&eacute;s) para simplificar su atenci&oacute;n m&eacute;dica y poder coordinarla de la mejor manera. Un HIE es una v&iacute;a para compartir informaci&oacute;n m&eacute;dica con otros proveedores de atenci&oacute;n de la salud participantes a trav&eacute;s de medios seguros y electr&oacute;nicos; de esta manera, los proveedores de atenci&oacute;n de la salud tienen el beneficio de contar con la informaci&oacute;n m&aacute;s actualizada que haya disponible.</span></p>
<p>&nbsp;</p>
<p><span style="font-weight: 400;">Las leyes estatales y federales establecen c&oacute;mo debe intercambiarse y usarse su informaci&oacute;n m&eacute;dica. FNN se compromete a proteger su informaci&oacute;n m&eacute;dica electr&oacute;nica y a mantener su privacidad, y solo podr&aacute;n obtener acceso a su informaci&oacute;n quienes lo pidan para brindarle atenci&oacute;n o para coordinarla, para hacer referencias, o seg&uacute;n lo exija la ley.</span></p>
<p>&nbsp;</p>
<p><span style="font-weight: 400;">ESTE FORMULARIO ES OPCIONAL. La participaci&oacute;n es voluntaria y no afectar&aacute; su capacidad para recibir atenci&oacute;n m&eacute;dica. Si usted no acepta participar, el HIE bloquear&aacute; el acceso a su informaci&oacute;n m&eacute;dica, y toda la informaci&oacute;n m&eacute;dica sobre usted que reciban los proveedores o afiliados de FNN NO SER&Aacute; VISIBLE en los HIE en los que FNN participe. Esto significa que sus proveedores de atenci&oacute;n de la salud pueden tardar m&aacute;s tiempo en obtener la informaci&oacute;n m&eacute;dica que podr&iacute;an necesitar para brindarle tratamiento. ESTO PUEDE INCLUIR SITUACIONES DE EMERGENCIA. Aunque no desee participar en los HIE, se cumplir&aacute; con los requisitos de informaci&oacute;n impuestos por las leyes estatales a trav&eacute;s de los Registros de Salud P&uacute;blica.</span></p>
<p>&nbsp;</p>
<p><span style="font-weight: 400;">TENGA EN CUENTA LO SIGUIENTE: Siempre es conveniente asegurarse de que su proveedor de atenci&oacute;n de la salud conozca todos sus problemas de salud y los medicamentos que toma.</span></p>
<p>&nbsp;</p>
<p><span style="font-weight: 400;">ACEPTACI&Oacute;N: Mediante este documento, doy permiso a FNN para que haga visible mi informaci&oacute;n en los HIE en los que FNN participe.</span></p>
<ul>
<li style="font-weight: 400;"><span style="font-weight: 400;">Entiendo que toda la informaci&oacute;n m&eacute;dica sobre m&iacute; que reciban los proveedores o afiliados de FNN SER&Aacute; VISIBLE en los HIE en los que FNN participe.</span></li>
<li style="font-weight: 400;"><span style="font-weight: 400;">Entiendo que tengo la libertad de cancelar este formulario de aceptaci&oacute;n en cualquier momento y que, para hacerlo, debo comunicarme con FNN.</span></li>
<li style="font-weight: 400;"><span style="font-weight: 400;">Entiendo que esta solicitud solo aplica al intercambio de mi informaci&oacute;n m&eacute;dica mediante Intercambios de Informaci&oacute;n M&eacute;dica, y que un proveedor de atenci&oacute;n de la salud puede pedir y recibir mi informaci&oacute;n m&eacute;dica de otros proveedores mediante el uso de otros m&eacute;todos permitidos por la ley, como fax o correo electr&oacute;nico.</span></li>
</ul>
<p>&nbsp;</p>
<p><strong>AVISO DE PR&Aacute;CTICAS DE PRIVACIDAD DE FOODSMART NUTRITION NETWORK</strong></p>
<p>&nbsp;</p>
<p><strong>ESTE AVISO DESCRIBE C&Oacute;MO SE PUEDE USAR Y REVELAR SU INFORMACI&Oacute;N M&Eacute;DICA Y DE QU&Eacute; MANERA PUEDE OBTENER ACCESO A ESTA INFORMACI&Oacute;N. L&Eacute;ALO DETENIDAMENTE.</strong></p>
<p>&nbsp;</p>
<p><span style="font-weight: 400;">Este Aviso de Pr&aacute;cticas de Privacidad (el &ldquo;Aviso&rdquo;) describe c&oacute;mo Foodsmart Nutrition Network ("FNN", que lleva adelante sus actividades comerciales mediante los grupos de proveedores legales de Zipongo Health Provider Group, P.A., una entidad que opera con los nombres comerciales de Foodsmart Nutrition Network; Foodsmart Nutrition Network of New Jersey, P.C.; Foodsmart Nutrition Network of Kansas, P.A.; y David Ashley, MD, P.C., en conjunto, Foodsmart Nutrition Network) (&ldquo;nosotros&rdquo; o &ldquo;nuestro/a/os/as&rdquo;) puede usar y revelar su informaci&oacute;n m&eacute;dica protegida para fines de tratamiento, pagos u operaciones comerciales, o para otros fines permitidos o exigidos por la ley. La &ldquo;informaci&oacute;n m&eacute;dica protegida&rdquo; (o &ldquo;PHI&rdquo;, por sus siglas en ingl&eacute;s) es informaci&oacute;n sobre usted, incluida la informaci&oacute;n demogr&aacute;fica, que puede usarse para determinar su identidad y que se relaciona con su salud o condici&oacute;n f&iacute;sica, sus tratamientos o el pago de servicios de atenci&oacute;n m&eacute;dica, en el pasado, presente o futuro. Este Aviso tambi&eacute;n describe el derecho que tiene para obtener acceso a su informaci&oacute;n m&eacute;dica protegida y controlarla.</span></p>
<p>&nbsp;</p>
<p><strong>USOS Y REVELACIONES DE LA INFORMACI&Oacute;N M&Eacute;DICA PROTEGIDA:</strong></p>
<p>&nbsp;</p>
<p><span style="font-weight: 400;">Nuestros proveedores de atenci&oacute;n de la salud, nuestro personal y personas ajenas a nuestro centro que participan en su atenci&oacute;n y tratamiento pueden usar y revelar su informaci&oacute;n m&eacute;dica protegida para brindarle servicios de atenci&oacute;n m&eacute;dica, brindar apoyo a nuestras operaciones comerciales, obtener los pagos correspondientes a su atenci&oacute;n, y para cualquier otro uso autorizado o exigido por la ley.</span></p>
<p>&nbsp;</p>
<p><strong>TRATAMIENTO:</strong></p>
<p>&nbsp;</p>
<p><span style="font-weight: 400;">Usaremos y revelaremos su informaci&oacute;n m&eacute;dica protegida para brindar, coordinar o administrar su atenci&oacute;n m&eacute;dica y todos los servicios relacionados. Esto incluye la coordinaci&oacute;n o administraci&oacute;n de su atenci&oacute;n m&eacute;dica con un tercero. Por ejemplo, su informaci&oacute;n m&eacute;dica protegida podr&iacute;a compartirse con el proveedor de atenci&oacute;n de la salud al que haya sido referido para garantizar el acceso a la informaci&oacute;n necesaria para brindarle un diagn&oacute;stico o tratamiento.</span></p>
<p>&nbsp;</p>
<p><strong>PAGO:</strong></p>
<p>&nbsp;</p>
<p><span style="font-weight: 400;">Su informaci&oacute;n m&eacute;dica protegida puede usarse para facturar u obtener el pago correspondiente a sus servicios de atenci&oacute;n m&eacute;dica. Esto podr&iacute;a incluir ciertas actividades que su plan de seguro de salud puede llevar a cabo antes de aprobar o pagar sus servicios, por ejemplo: hacer una determinaci&oacute;n de elegibilidad o cobertura para beneficios de seguro y analizar los servicios que se le brindan por necesidad m&eacute;dica.</span></p>
<p>&nbsp;</p>
<p><strong>ACTIVIDADES RELACIONADAS CON LA ATENCI&Oacute;N M&Eacute;DICA:</strong></p>
<p>&nbsp;</p>
<p><span style="font-weight: 400;">Podemos usar o revelar su informaci&oacute;n m&eacute;dica protegida seg&uacute;n sea necesario para brindar apoyo a las actividades comerciales de este centro. Estas actividades incluyen, entre otras, mejorar la calidad de la atenci&oacute;n; brindar informaci&oacute;n sobre alternativas de tratamiento u otros beneficios y servicios relacionados con la salud; desarrollar o mantener y brindar soporte de sistemas inform&aacute;ticos; obtener servicios legales; y llevar a cabo auditor&iacute;as y programas de cumplimiento, incluso investigaciones relacionadas con fraude, desperdicio y abuso.</span></p>
<p>&nbsp;</p>
<p><strong>USOS Y REVELACIONES QUE NO REQUIEREN SU AUTORIZACI&Oacute;N:</strong></p>
<p>&nbsp;</p>
<p><span style="font-weight: 400;">Podemos usar o revelar su informaci&oacute;n m&eacute;dica protegida sin su autorizaci&oacute;n en las siguientes situaciones, que incluyen los siguientes usos y revelaciones: seg&uacute;n lo exija la ley; para fines de salud p&uacute;blica; para fines de supervisi&oacute;n de la atenci&oacute;n m&eacute;dica; para denuncias de abuso o negligencia; seg&uacute;n los requisitos de la Food and Drug Administration (Administraci&oacute;n de Alimentos y Medicamentos); en relaci&oacute;n con procedimientos legales; para fines de cumplimiento de la ley; para m&eacute;dicos forenses, directores de funerarias y agencias de donaci&oacute;n de &oacute;rganos; para ciertos fines de investigaci&oacute;n; para ciertas actividades delictivas; para cierta actividad militar y para fines de seguridad nacional; para informes relacionados con compensaciones por accidentes de trabajo; en relaci&oacute;n con ciertas declaraciones de reclusos; y otros usos y revelaciones requeridos. En cumplimiento de la ley, debemos hacerle ciertas revelaciones cuando usted lo pida, y cuando as&iacute; lo exija el secretario del Department of Health and Human Services (Departamento de Salud y Servicios Humanos) para investigar o determinar nuestro cumplimiento con los requisitos de la Health Insurance Portability and Accountability Act (HIPAA, Ley de Portabilidad y Responsabilidad de Seguros M&eacute;dicos). Es posible que las leyes estatales impongan restricciones adicionales a estas revelaciones.</span></p>
<p>&nbsp;</p>
<p><strong>USOS Y REVELACIONES QUE REQUIEREN SU AUTORIZACI&Oacute;N:</strong></p>
<p>&nbsp;</p>
<p><span style="font-weight: 400;">Los dem&aacute;s usos y revelaciones permitidos y exigidos solo se har&aacute;n con su consentimiento y autorizaci&oacute;n, o siempre que tenga la oportunidad de oponerse, a menos que lo permita o exija la ley. Sin su autorizaci&oacute;n, se nos proh&iacute;be expresamente usar o revelar su informaci&oacute;n m&eacute;dica protegida con fines de comercializaci&oacute;n. No podemos vender su informaci&oacute;n m&eacute;dica protegida sin su autorizaci&oacute;n. No se usar&aacute; su informaci&oacute;n m&eacute;dica protegida para recaudar fondos. Si nos autoriza a hacer ciertos usos y revelaciones de su informaci&oacute;n, podr&aacute; cancelar la autorizaci&oacute;n en cualquier momento por escrito, salvo que ya hayamos tomado alguna medida respaldada por el uso o la revelaci&oacute;n descritos en la autorizaci&oacute;n.</span></p>
<p><span style="font-weight: 400;">Este Aviso se public&oacute; originalmente el 1 de enero de 2020 y tiene validez a partir de esa fecha.</span></p>
<p><strong>SUS DERECHOS CON RESPECTO A SU INFORMACI&Oacute;N M&Eacute;DICA PROTEGIDA:</strong></p>
<p>&nbsp;</p>
<p><span style="font-weight: 400;">Tiene derecho a revisar y copiar su informaci&oacute;n m&eacute;dica protegida.</span></p>
<p>&nbsp;</p>
<p><span style="font-weight: 400;">Puede pedir obtener acceso a su informaci&oacute;n m&eacute;dica protegida o que se la modifique.</span></p>
<p>&nbsp;</p>
<p><span style="font-weight: 400;">Tiene derecho a pedir restricciones en cuanto al uso o la revelaci&oacute;n de su informaci&oacute;n m&eacute;dica/personal protegida. Debe hacer el pedido por escrito y especificar cu&aacute;l es la restricci&oacute;n que pide y a qui&eacute;n desea que se le aplique. No estamos obligados a estar de acuerdo con las restricciones que usted pudiera pedir, excepto cuando se trate de una revelaci&oacute;n hecha a un plan de salud con fines relacionados con pagos u actividades de atenci&oacute;n m&eacute;dica con respecto a un servicio que se haya pagado completamente del bolsillo.</span></p>
<p>&nbsp;</p>
<p><span style="font-weight: 400;">Tiene derecho a pedir que le enviemos comunicaciones confidenciales a trav&eacute;s de medios alternativos o en un lugar alternativo. Cumpliremos con todos los pedidos razonables que se presenten por escrito y que especifiquen c&oacute;mo o d&oacute;nde desea recibir estas comunicaciones.</span></p>
<p>&nbsp;</p>
<p><span style="font-weight: 400;">Tiene derecho a pedir que se modifique su informaci&oacute;n m&eacute;dica protegida. Si rechazamos su pedido para modificarla, tiene derecho a presentarnos una declaraci&oacute;n de desacuerdo. Podremos impugnar su declaraci&oacute;n y, si este es el caso, le entregaremos una copia de la impugnaci&oacute;n.</span></p>
<p>&nbsp;</p>
<p><span style="font-weight: 400;">Tiene derecho a recibir una explicaci&oacute;n de ciertas revelaciones que hayamos hecho, en formato impreso o electr&oacute;nico, en relaci&oacute;n con su informaci&oacute;n m&eacute;dica protegida, excepto en el caso de ciertas revelaciones que se hayan hecho de acuerdo con una autorizaci&oacute;n, para el tratamiento, el pago o las actividades de atenci&oacute;n m&eacute;dica (a menos que la informaci&oacute;n se mantenga en un registro de salud electr&oacute;nico), o para otros fines determinados.</span></p>
<p>&nbsp;</p>
<p><span style="font-weight: 400;">Tiene derecho a pedir y recibir una copia impresa de este Aviso, incluso cuando ya haya pedido el recibo digital por correo electr&oacute;nico.</span></p>
<p>&nbsp;</p>
<p><strong>MODIFICACIONES A ESTE AVISO:</strong></p>
<p>&nbsp;</p>
<p><span style="font-weight: 400;">Nos reservamos el derecho a modificar este Aviso y a establecer que la versi&oacute;n actualizada de este tenga validez tanto para la informaci&oacute;n m&eacute;dica protegida que ya tenemos sobre usted como para la que recibamos en el futuro. Tiene derecho a recibir una copia del Aviso con validez actual. Cualquier cambio significativo que se le haga a este Aviso se publicar&aacute; en nuestro sitio web. En ese momento, tendr&aacute; derecho a oponerse o a retirar su consentimiento seg&uacute;n se describe en este Aviso.</span></p>
<p>&nbsp;</p>
<p><strong>INCUMPLIMIENTO RELACIONADO CON LA INFORMACI&Oacute;N M&Eacute;DICA:</strong></p>
<p>&nbsp;</p>
<p><span style="font-weight: 400;">Le enviaremos una notificaci&oacute;n si se descubre que hubo un incumplimiento que deba informarse en relaci&oacute;n con su informaci&oacute;n m&eacute;dica protegida vulnerable. La notificaci&oacute;n le llegar&aacute; dentro de los 60 d&iacute;as posteriores a que se haya descubierto el incumplimiento e incluir&aacute; una breve descripci&oacute;n de la manera en que ocurri&oacute; el incumplimiento, la informaci&oacute;n m&eacute;dica protegida afectada y la informaci&oacute;n de contacto para que pueda hacer preguntas.}</span></p>
<p>&nbsp;</p>
<p><strong>QUEJAS:</strong></p>
<p>&nbsp;</p>
<p><span style="font-weight: 400;">Las quejas relacionadas con este Aviso o con la manera en que administramos su informaci&oacute;n m&eacute;dica protegida deben presentarse ante el Funcionario de Privacidad de HIPAA. Si no est&aacute; conforme con la manera en que se trata una queja, puede presentar una queja formal ante la Office for Civil Rights (Oficina de Derechos Civiles) del Department of Health and Human Services (Departamento de Salud y Servicios Humanos) enviando una carta a 200&nbsp;Independence&nbsp;Avenue,&nbsp;S.W.,&nbsp;Washington,&nbsp;D.C. 20201, llamando al 1-877-696-6775 o visitando&nbsp;</span><a href="http://www.hhs.gov/ocr/privacy/hipaa/complaints/"><span style="font-weight: 400;">www.hhs.gov/ocr/privacy/hipaa/complaints/.</span></a><span style="font-weight: 400;"> No tomaremos represalias contra usted por presentar una queja.</span></p>
<p>&nbsp;</p>
<p><span style="font-weight: 400;">Debemos cumplir con las obligaciones y las pr&aacute;cticas de privacidad que se describen en este Aviso. Mantendremos la privacidad de su informaci&oacute;n m&eacute;dica protegida y notificaremos a las personas afectadas por un incumplimiento relacionado con informaci&oacute;n m&eacute;dica protegida vulnerable. Si tiene alguna pregunta sobre este Aviso, comun&iacute;quese con nosotros al 888-837-5325 y pida hablar con nuestro Funcionario de Privacidad de HIPAA.</span></p>
<p>&nbsp;</p>
<p><strong>CONFIRMACI&Oacute;N DE RECEPCI&Oacute;N DEL AVISO DE PR&Aacute;CTICAS DE PRIVACIDAD</strong></p>
<p><span style="font-weight: 400;">Usted confirma que ha recibido, o que le han dado la oportunidad de recibir, el Aviso de Pr&aacute;cticas de Privacidad de FNN.</span></p>
<p>&nbsp;</p>
<p><span style="font-weight: 400;">He recibido o me han dado la oportunidad de recibir el Aviso de Pr&aacute;cticas de Privacidad de FNN.</span></p>
<p>&nbsp;</p>
<p><span style="font-weight: 400;">Si usted es uno de los padres o el representante personal del paciente, confirma en nombre del paciente que ha recibido o que le han dado la oportunidad de recibir el Aviso de Pr&aacute;cticas de Privacidad de FNN.</span></p>
<p>&nbsp;</p>
<p><strong>Consentimiento para recibir llamadas telef&oacute;nicas</strong></p>
<p><span style="font-weight: 400;">El paciente autoriza al centro a usar la informaci&oacute;n brindada como parte del proceso de registro para que lo contacten mediante correos electr&oacute;nicos y llamadas telef&oacute;nicas. Esto incluye lo siguiente: al ingresar un n&uacute;mero de tel&eacute;fono de contacto, se da consentimiento por escrito para recibir llamadas telef&oacute;nicas automatizadas, pregrabadas y por voz artificial de parte del centro. Para modificar o cancelar este consentimiento, visite &ldquo;Contact Preferences&rdquo; (Preferencias de contacto) en el Portal para pacientes.</span></p>
<p>&nbsp;</p>
<p><strong>Consentimiento para recibir mensajes de texto</strong></p>
<p>&nbsp;</p>
<p><span style="font-weight: 400;">El</span><strong> Consentimiento para recibir mensajes de texto </strong><span style="font-weight: 400;">indica si el paciente ha aceptado recibir alertas automatizadas por mensaje de texto en su tel&eacute;fono celular de parte del centro. Seg&uacute;n las opciones que ofrezca el centro, las alertas por mensaje de texto pueden ser sobre citas, resultados de pruebas, etc. El paciente autoriza para recibir mensajes de texto.</span></p>
<p><br /><br /></p>
`;

export default html;
