-- migrate:up

INSERT INTO "common"."account"
  ( "account_id", "name", "active" )
VALUES
  ( 2, 'Maricopa County', true ),
  ( 3, 'Sandia', true ),
  ( 4, 'VP+ 3DS Dassault Systems', true ),
  ( 5, 'VP+ ACEC Life/Health Trust', true ),
  ( 6, 'Independent Health', true ),
  ( 7, 'VP+ Acushnet Company', true ),
  ( 8, 'Martin''s Point GA',	true ),
  ( 9, 'CCHP - Medicaid', true ),
  ( 10, 'CCHP - Exchange', true ),
  ( 11,	'Umpqua - Medicaid', true ),
  ( 12,	'VP+ Amadeus North America Inc.', true ),
  ( 13,	'VP+ American Cancer Society', true ),
  ( 14,	'VP+ American Family Insurance', true ),
  ( 16,	'US House of Representatives', true ),
  ( 17,	'VP+ Ameritas Life Insurance Corp.', true ),
  ( 18,	'VP+ Amneal Pharmaceuticals', true ),
  ( 19,	'Umpqua - Employees', true ),
  ( 20,	'Cigna House', true ),
  ( 21,	'FedEx (Cigna)', true ),
  ( 22,	'MNPS (Cigna)', true ),
  ( 23,	'Smith & Nephew (Cigna)', true ),
  ( 24,	'Phoenix Children''s Hospital', true ),
  ( 25,	'ArcBest', true ),
  ( 26,	'Dean Health Plan', true ),
  ( 27,	'Aetna Medicare', true ),
  ( 29,	'UHC DSNP', true ),
  ( 30,	'HSCSN', true ),
  ( 31,	'SEI (Cigna)', true ),
  ( 32,	'City of Clearwater', true ),
  ( 33,	'Cigna National', true ),
  ( 34,	'Stryker', true ),
  ( 35,	'Florida Blue Medicare', true ),
  ( 36,	'Arizona Public Schools (Cigna)', true ),
  ( 37,	'Banner Health', true ),
  ( 38,	'CDPHP', true ),
  ( 39,	'AAH', true ),
  ( 40,	'AAH Provider', true ),
  ( 41,	'BCBSIL', true ),
  ( 42,	'BCBSTX', true ),
  ( 43,	'Biomerieux', true ),
  ( 44,	'Centura Health Corporation', true ),
  ( 46,	'CountyCare', true ),
  ( 47,	'EPAM (Cigna)', true ),
  ( 48,	'Ford', true ),
  ( 49,	'Healthfirst', true ),
  ( 50,	'M&T Bank', true ),
  ( 51,	'Martin''s Point Health Care Inc.', true ),
  ( 52,	'Molina', true ),
  ( 53,	'NorthwesternMutual', true ),
  ( 54,	'Ohio Health', true ),
  ( 55,	'PacificSource', true ),
  ( 56,	'Quartz', true ),
  ( 57,	'Salesforce', true ),
  ( 58,	'Suez WTD (Cigna)', true )
ON CONFLICT DO NOTHING 
;

-- migrate:down

