-- migrate:up

-- legacy athena tables, should be dropped once all data is migrated

CREATE TABLE IF NOT EXISTS "athena_stage"."customdemographics_raw" (
    "contextid" bigint,
    "contextname" character varying(65535),
    "contextparentcontextid" bigint,
    "clientrecordnumberid" bigint,
    "patientid" bigint,
    "customfieldname" character varying(65535),
    "customfieldtype" character varying(65535),
    "customfieldvalue" character varying(65535),
    "deleteddatetime" timestamp without time zone,
    "deletedby" character varying(65535),
    "lastupdated" timestamp without time zone,
    "recordnumberselectid" bigint,
    "recordnumbercategoryid" bigint,
    "recordnumbercategoryselectyn" character varying(65535),
    "createdby" character varying(65535),
    "createddatetime" timestamp without time zone
);

CREATE TABLE IF NOT EXISTS "athena_stage"."appointment_raw" (
    "contextid" bigint,
    "contextname" character varying(65535),
    "contextparentcontextid" bigint,
    "appointmentid" bigint,
    "parentappointmentid" bigint,
    "appointmentdate" date,
    "appointmentstarttime" character varying(65535),
    "appointmentcreateddatetime" timestamp without time zone,
    "appointmentcreatedby" character varying(65535),
    "appointmentscheduleddatetime" timestamp without time zone,
    "scheduledby" character varying(65535),
    "scheduledbymdppartnername" character varying(65535),
    "appointmentcheckindatetime" timestamp without time zone,
    "checkedinby" character varying(65535),
    "appointmentcheckoutdatetime" timestamp without time zone,
    "checkedoutby" character varying(65535),
    "appointmentcancelleddatetime" timestamp without time zone,
    "cancelledby" character varying(65535),
    "cancelledbymdppartnername" character varying(65535),
    "startcheckindatetime" timestamp without time zone,
    "stopsignoffdatetime" timestamp without time zone,
    "rescheduledappointmentid" bigint,
    "rescheduleddatetime" timestamp without time zone,
    "rescheduledby" character varying(65535),
    "rescheduledbymdppartnername" character varying(65535),
    "appointmentstatus" character varying(65535),
    "frozenyn" character varying(65535),
    "appointmentfrozenreason" character varying(65535),
    "appointmenttypeid" bigint,
    "appointmentduration" smallint,
    "nochargeentryreason" character varying(65535),
    "appointmentcancelreason" character varying(65535),
    "claimid" bigint,
    "primarypatientinsuranceid" bigint,
    "secondarypatientinsuranceid" bigint,
    "patientid" bigint,
    "departmentid" bigint,
    "schedulingprovider" character varying(65535),
    "schedulingproviderid" bigint,
    "providerid" bigint,
    "referringproviderid" bigint,
    "referralauthid" bigint,
    "cycletime" numeric(24,6),
    "patientoutstandingamount" numeric(12,2),
    "patientoutstandingcollected" numeric(12,2),
    "collectionsamount" numeric(12,2),
    "collectionsamountcollected" numeric(12,2),
    "patientunappliedamount" numeric(12,2),
    "patientunappliedcollected" numeric(12,2),
    "patientfamilyoutstandingamt" numeric(12,2),
    "familyoutstandingcollected" numeric(12,2),
    "patientfamilycollectionamt" numeric(12,2),
    "familycollectioncollected" numeric(12,2),
    "patientoutstandingpmtchoice" character varying(65535),
    "paymentplanid" bigint,
    "appointmentdeleteddatetime" timestamp without time zone,
    "appointmentdeletedby" character varying(65535),
    "nochargeentrysignoff" character varying(65535),
    "appmtscheduleddatetimeast" timestamp without time zone,
    "appointmenttypeblockid" bigint,
    "schedulingtemplateid" bigint,
    "suggestedoverbooking" bigint,
    "slotactionid" bigint,
    "forcedyn" character varying(65535),
    "templateappointmentid" bigint,
    "templateappointmenttypeid" bigint,
    "localpatientappointmentlabelid" bigint,
    "localpatientappointmentlabelname" character varying(65535),
    "groupcheckinappointmentid" bigint,
    "initialepaymentcontractid" bigint,
    "epaymentcontractid" bigint,
    "appointmentconfirmationid" bigint,
    "appointmentlastmodifieddatetime" timestamp without time zone,
    "appointmentlastmodifiedby" character varying(65535),
    "lastupdated" timestamp without time zone,
    "appointmentcancelreasonid" bigint,
    "patientoutstandingpmtchoicereason" character varying(65535),
    "patientoutstandingpmtchoiceid" bigint,
    "startcheckoutdatetime" timestamp without time zone,
    "stopcheckindatetime" timestamp without time zone,
    "stopcheckoutdatetime" timestamp without time zone,
    "deferinsuranceyn" character varying(65535)
);

CREATE TABLE IF NOT EXISTS "athena_stage"."patientinsurance_raw" (
    "contextid" bigint,
    "contextname" character varying(65535),
    "contextparentcontextid" bigint,
    "patientinsuranceid" bigint,
    "patientid" bigint,
    "insurancepackageid" bigint,
    "sequencenumber" character varying(65535),
    "issuedate" date,
    "expirationdate" date,
    "cancellationdate" date,
    "policyidnumber" character varying(65535),
    "policygroupnumber" character varying(65535),
    "pcpid" bigint,
    "employerid" bigint,
    "entitytype" character varying(65535),
    "policyholderid" bigint,
    "policyholderidnumber" character varying(65535),
    "policyholderhipaaid" character varying(65535),
    "firstname" character varying(65535),
    "lastname" character varying(65535),
    "middlename" character varying(65535),
    "suffix" character varying(65535),
    "address" character varying(65535),
    "address2" character varying(65535),
    "city" character varying(65535),
    "state" character varying(65535),
    "zip" character varying(65535),
    "country" character varying(65535),
    "homephone" character varying(65535),
    "dob" date,
    "sex" character varying(65535),
    "ssn" character varying(65535),
    "employername" character varying(65535),
    "patientrelationship" character varying(65535),
    "adjustername" character varying(65535),
    "adjusterphone" character varying(65535),
    "adjusterfax" character varying(65535),
    "slidingfeeplanid" bigint,
    "eligibilitystatus" character varying(65535),
    "statusreason" character varying(65535),
    "paymentplanid" bigint,
    "eligibilityservicedate" date,
    "eligibilitylastchecked" timestamp without time zone,
    "eligibilitylastcheckedby" character varying(65535),
    "caseinjurydate" timestamp without time zone,
    "createddatetime" timestamp without time zone,
    "createdby" character varying(65535),
    "deleteddatetime" timestamp without time zone,
    "lastupdated" timestamp without time zone,
    "eligibilitytrackid" bigint,
    "insurancecity" character varying(65535),
    "insuranceoverridezip" character varying(65535),
    "gatekeeperflagyn" character varying(65535),
    "eligibilityreasonid" character varying(65535),
    "relationshiptoinsuredid" bigint,
    "workcompstate" character varying(65535),
    "plcinsuredfirstname" character varying(65535),
    "coinsurancepercent" numeric(11,2),
    "interfacevendorid" character varying(65535),
    "anotherpartyresponsibleyn" character varying(65535),
    "plcinsuredcity" character varying(65535),
    "autoaccidentstate" character varying(65535),
    "mspinsurancetypeid" bigint,
    "slidingfeeprogramid" bigint,
    "repricername" character varying(65535),
    "plcinsuredlastname" character varying(65535),
    "foreigninsurancepackagename" character varying(65535),
    "insuranceoverridecontactname" character varying(65535),
    "insurancecopay" bigint,
    "pendinginsurancepackageid" character varying(65535),
    "diagnosiscodes" character varying(65535),
    "pcpprovidernumber" character varying(65535),
    "enterpriseid" bigint,
    "lastmodifiedby" character varying(65535),
    "injuredbodypart" character varying(65535),
    "foreigninsurancepackagestate" character varying(65535),
    "diagnosiscodesicd10" character varying(65535),
    "foreigninsurancepackagecode" character varying(65535),
    "shortname" character varying(65535),
    "plcinsuredaddress" character varying(65535),
    "updateeligibilitytrackid" bigint,
    "insuranceoverrideaddress2" character varying(65535),
    "mspinsurancetypesetyn" character varying(65535),
    "plcinsuredaddress2" character varying(65535),
    "casenumber" character varying(65535),
    "insuredentitytypeid" bigint,
    "pcpname" character varying(65535),
    "sourceerarecordid" bigint,
    "foreigninsurancepackageaddress" character varying(65535),
    "definsurancepackageaddressid" bigint,
    "insurancecontactname" character varying(65535),
    "insurancephone" character varying(65535),
    "insuranceoverridecity" character varying(65535),
    "plcadjusterfirstname" character varying(65535),
    "foreigninsurancepackagephone" character varying(65535),
    "insurancenetworkcategoryid" bigint,
    "referralnumber" character varying(65535),
    "eligibilityupdatetimestampdatetime" timestamp without time zone,
    "eligibilityupdatereason" character varying(65535),
    "injurydescription" character varying(65535),
    "relatedtoautoaccidentyn" character varying(65535),
    "insuranceoverrideaddress" character varying(65535),
    "hascasenumberyn" character varying(65535),
    "relationshiptopatient" character varying(65535),
    "verificationnote" character varying(65535),
    "oldinsurancepackageid" bigint,
    "healthexchangetypeid" bigint,
    "insuranceproductcode" character varying(65535),
    "copaysource" character varying(65535),
    "relatedtootheraccidentyn" character varying(65535),
    "repricerphone" character varying(65535),
    "insuranceproducttypeid" character varying(65535),
    "patiententerpriseid" bigint,
    "insuredcountryid" bigint,
    "insuranceoverridename" character varying(65535),
    "notes" character varying(65535),
    "insurancestate" character varying(65535),
    "insuranceoverridecountry" character varying(65535),
    "insurancename" character varying(65535),
    "referringproviderid" bigint,
    "plcinsuredmiddleinitial" character varying(65535),
    "verificationnotelong" character varying(65535),
    "insuranceaddress" character varying(65535),
    "insuranceoverridephone" character varying(65535),
    "copay" numeric(12,2),
    "insuranceoverridestate" character varying(65535),
    "deletednote" character varying(65535),
    "wcbnumber" character varying(65535),
    "plcadjusterlastname" character varying(65535),
    "foreigninsurancepackagezip" character varying(65535),
    "accidentdatedatetime" timestamp without time zone,
    "originalpatientinsuranceid" bigint,
    "foreigninsurancepackagecity" character varying(65535),
    "insurancezip" character varying(65535),
    "defaultpackageyn" character varying(65535),
    "eligibilitymessage" character varying(65535),
    "foreignid" character varying(65535),
    "cancelledby" character varying(65535),
    "relatedtoemploymentyn" character varying(65535),
    "lastmodifieddatetime" timestamp without time zone,
    "deletedby" character varying(65535)
);

CREATE TABLE IF NOT EXISTS "athena_stage"."insurancepackage_raw" (
    "contextid" bigint,
    "contextname" character varying(65535),
    "contextparentcontextid" bigint,
    "insurancepackageid" bigint,
    "name" character varying(65535),
    "adjudicationprogramid" character varying(65535),
    "feeschedulecategoryid" character varying(65535),
    "insurancereportingcategoryid" bigint,
    "providernumbercategoryid" character varying(65535),
    "claimrulecategoryid" bigint,
    "ordering" bigint,
    "copaybase" numeric(22,2),
    "copaypercentage" numeric(22,2),
    "copaycap" numeric(22,2),
    "piggybackyn" character varying(65535),
    "claimformat" character varying(65535),
    "address" character varying(65535),
    "address2" character varying(65535),
    "city" character varying(65535),
    "state" character varying(65535),
    "zip" character varying(65535),
    "attachmentfax" character varying(65535),
    "contactname" character varying(65535),
    "phone" character varying(65535),
    "fax" character varying(65535),
    "status" character varying(65535),
    "otherid" character varying(65535),
    "emccode" character varying(65535),
    "emcreceivertype" character varying(65535),
    "emcofficecode" character varying(65535),
    "numpatientswiththisinsurance" bigint,
    "includeinoptions" character varying(65535),
    "emcreceiverid" bigint,
    "medigap" character varying(65535),
    "acceptassignmentyn" character varying(65535),
    "notes" character varying(65535),
    "practicenotes" character varying(65535),
    "eligibilityclass" character varying(65535),
    "suppressaddressyn" character varying(65535),
    "altnames" character varying(65535),
    "idnumberformat" character varying(65535),
    "invalididnumberformat" character varying(65535),
    "kickreasoncategoryid" bigint,
    "expecteddaystoeob" bigint,
    "pendingyn" character varying(65535),
    "changerequest" character varying(65535),
    "requestedbyphone" character varying(65535),
    "firstpatientid" bigint,
    "benefitsphone" character varying(65535),
    "billingphone" character varying(65535),
    "otherphone" character varying(65535),
    "acceptpatientsyn" character varying(65535),
    "oldidnumberformat" character varying(65535),
    "projectedcategoryid" bigint,
    "expectedcategoryid" bigint,
    "noninsurancetypeid" character varying(65535),
    "iderrortext" character varying(65535),
    "receptionistnotes" character varying(65535),
    "insuranceproducttypeid" character varying(65535),
    "producttypeid" bigint,
    "usualsequencenumber" character varying(65535),
    "claimsubmissioncategoryid" bigint,
    "sourcepracticeid" bigint,
    "coinsuranceyn" character varying(65535),
    "printzerodollarchargesyn" character varying(65535),
    "referralclass" character varying(65535),
    "referralrulecategoryid" bigint,
    "csiclass" character varying(65535),
    "allowablecategoryid" bigint,
    "appealsaddress" character varying(65535),
    "appealsaddress2" character varying(65535),
    "appealscity" character varying(65535),
    "appealsstate" character varying(65535),
    "appealszip" character varying(65535),
    "appealscontactname" character varying(65535),
    "appealsphone" character varying(65535),
    "appealsfax" character varying(65535),
    "appealsattachmentfax" character varying(65535),
    "appealsname" character varying(65535),
    "appealsattention" character varying(65535),
    "appealscountryid" bigint,
    "autoassignonlyyn" character varying(65535),
    "pickerserviceclass" character varying(65535),
    "insurancenetworkcategoryid" bigint,
    "country" character varying(65535),
    "allowaddressoverrideyn" character varying(65535),
    "countryid" bigint,
    "noathenafollowupyn" character varying(65535),
    "insurancepackagemassupdateid" bigint,
    "originalrequestby" character varying(65535),
    "originalrequestdatedatetime" timestamp without time zone,
    "cmsplanid" character varying(65535),
    "insurancetypeid" character varying(65535),
    "currentlymappedtoid" bigint,
    "generatetracelettersyn" character varying(65535),
    "ansiclaimfilingindicatorid" bigint,
    "effectivedatedatetime" timestamp without time zone,
    "expirationdatedatetime" timestamp without time zone,
    "website" character varying(65535),
    "enrollmentcategoryid" bigint,
    "governmentfundedyn" character varying(65535),
    "governmentfundedtypeid" bigint,
    "routingprogramid" bigint,
    "csiclassid" bigint,
    "hsrclassid" bigint,
    "coordinatorinsurancecategoryid" bigint,
    "standalonecoordinatoryn" character varying(65535),
    "attention" character varying(65535),
    "standaloneclinicalsyn" character varying(65535),
    "sendpatientassubscriberyn" character varying(65535),
    "parentinsurancepackageid" bigint,
    "checkmedicalnecessityyn" character varying(65535),
    "invoicecoversheetyn" character varying(65535),
    "invoicesubmitoverdueyn" character varying(65535),
    "invoicesubmitcorrectedyn" character varying(65535),
    "invoiceoverduedays" smallint,
    "invoicesendviaemailyn" character varying(65535),
    "invoiceemailaddress" character varying(65535),
    "invoiceshowadjustmentsyn" character varying(65535),
    "invoicecontactinfo" character varying(65535),
    "invoicepurchaseordernumber" character varying(65535),
    "definsurancepackageaddressid" bigint,
    "definsurancepackagephoneid" bigint,
    "stateofcoverage" character varying(65535),
    "requestreasonid" bigint,
    "formername" character varying(65535),
    "superpackagename" character varying(65535),
    "packagecreatereasonid" bigint,
    "packagecreatereasonnotes" character varying(65535),
    "invsubcorrecteddatedatetime" timestamp without time zone,
    "invsuboverduedatedatetime" timestamp without time zone,
    "deleted" timestamp without time zone,
    "deletedby" character varying(65535),
    "created" timestamp without time zone,
    "createdby" character varying(65535),
    "lastmodified" timestamp without time zone,
    "lastmodifiedby" character varying(65535),
    "lastupdated" timestamp without time zone
);

GRANT SELECT ON ALL TABLES IN SCHEMA athena_stage TO svc_common;

-- migrate:down
